server:
  port: 8099

spring:
  application:
    name: microservice-feignservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

